### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by jeffbcross**
This re-generates the existing services, components, routes as-is, but using CLI. Currently app shell generation doesn't work because of the Jsonp dependency. Shouldn't be hard to mock that out and get app shell happy again, but I'm falling asleep :).

### CODE REVIEW

**Comment by jeffbcross** [comment]
I just published a new version of angular2-broccoli-prerender that should make this all work, including generating the app shell. So with this PR, if you npm install angular2-broccoli-prerender@0.11.5, ng serve should behave as expected.

**Comment by jeffbcross** [comment]
I added another commit to show how the `async` pipe could be used in a template to bind an observable directly to the template. This lets us use the ON_PUSH change detection strategy, which will only run change detection on the component if the observable pushes a new value. Using the `async` pipe instead of manually subscribing to observables inside the component also lets Angular take care of disposing of the observable when the component is destroyed.

**Comment by addyosmani** [comment]
Studied the changes you've made to this Progressive Beard App. The atomic commits are so helpful. Thanks a lot, @jeffbcross! 

A local checkout requires manually installing `@angular/service-worker` from toolkit before source can be built. I'm happy to add this back in, but wanted to check if a dep elsewhere in the tree was meant to pick this up (I cleared out my npm cache prior to installing just to check)

Cheers and a huge thanks again!

**Comment by jeffbcross** [comment]
1. The service worker dependency has been fixed upstream, but would only
   take effect when scaffolding a new project. So for this app it's best to
   manually install.
2. I must have forgotten to copy over some cases

Btw one of my teammates is working on adding automatic inclining of HTML
and CSS to the cli build pipeline which would fix the current limitation of
requiring inline templates for all shell.

**Comment by jeffbcross** [comment]
s/some cases/some CSS

**Pull request merged**
